name: UltimateClaims
description: 'Земли'
version: maven-version-number
softdepend: [PlayerPoints, HolographicDisplays, Holograms, CMI, Vault, dynmap, ItemsAdder, Slimefun, ItemBridge]
main: com.songoda.ultimateclaims.UltimateClaims
author: songoda
api-version: 1.13
loadbefore: [WorldGuard]
commands:
  c:
    description: 'Перезагружает файл конфигурации'
    default: true
    aliases: [claim]
    usage: /ultimateclaims reload
permissions:
  ultimateclaims.*:
    description: 'Наследует все разрешения плагина'
    children:
      ultimateclaims.bypass: true
      ultimateclaims.toggle.hostilemobspawning: true
      ultimateclaims.toggle.firespread: true
      ultimateclaims.toggle.pvp: true
      ultimateclaims.toggle.mobgriefing: true
      ultimateclaims.toggle.leafdecay: true
      ultimateclaims.accept: true
      ultimateclaims.ban: true
      ultimateclaims.claim: true
      ultimateclaims.dissolve: true
      ultimateclaims.home: true
      ultimateclaims.invite: true
      ultimateclaims.kick: true
      ultimateclaims.leave: true
      ultimateclaims.lock: true
      ultimateclaims.recipe: true
      ultimateclaims.sethome: true
      ultimateclaims.unban: true
      ultimateclaims.unclaim: true
  ultimateclaims.bypass:
    description: 'Позволяет игроку или администратору обойти ограничения по землям.'
    default: op
  ultimateclaims.toggle.hostilemobspawning:
    description: 'Позволяет владельцу земли переключать порождение толпы.'
    default: op
  ultimateclaims.toggle.firespread:
    description: 'Позволяет владельцу земли переключать распространение огня.'
    default: op
  ultimateclaims.toggle.pvp:
    description: 'Позволяет владельцу земли переключать pvp.'
    default: op
  ultimateclaims.toggle.mobgriefing:
    description: 'Позволяет владельцу претензии переключать скорбь толпы.'
    default: op
  ultimateclaims.toggle.leafdecay:
    description: 'Позволяет владельцу претензии переключать распад листьев.'
    default: op
  ultimateclaims.accept:
    description: 'Примите последнее приглашение на подачу заявки.'
    default: op
  ultimateclaims.ban:
    description: 'Запретить участника в земле.'
    default: op
  ultimateclaims.claim:
    description: 'Заприватьть землю для себя.'
    default: op
  ultimateclaims.dissolve:
    description: 'Аннулировать свою землю.'
    default: op
  ultimateclaims.home:
    description: 'Отправиться в дом земли.'
    default: op
  ultimateclaims.invite:
    description: 'Пригласить участника в землю.'
    default: op
  ultimateclaims.kick:
    description: 'Исключить участника из земли.'
    default: op
  ultimateclaims.leave:
    description: 'Выйти из земли.'
    default: op
  ultimateclaims.lock:
    description: 'Заблокировать или разблокировать свою землю.'
    default: op
  ultimateclaims.recipe:
    description: 'Посмотреть рецепт элемента питания.'
    default: op
  ultimateclaims.sethome:
    description: 'Установить дом земли.'
    default: op
  ultimateclaims.unban:
    description: 'Разблокировать участника земли.'
    default: op
  ultimateclaims.unclaim:
    description: 'Освободите землю от своих земель.'
    default: op